### ISSUE TITLE
Data Grid: documentation and optimization for using it in other frameworks

### ISSUE THREAD

**Issue by estruyf** [microsoft/vscode-webview-ui-toolkit#257]
### Feature/component description

Right now the Data Grid component sample shows you how to use it by binding your rows of data. 

When using a framework like React, Vue, ... It would be helpful to have an example of how to use the sub-components and their available attributes.

### Use case

I want to use the web components in React to create a data table on which I can loop through my rows and cells. To have more control over the rendering, using the sub-components is more suitable. 

Right now the documentation is missing for these components, although they are available to use. When you are not data binding with the `rowsData` property. You need to set a lot of the attributes yourself, is this something that can be simplified?

### Screenshots/references

Here is an example of how I'm currently using it in React:

```html
<VsDataGrid>
  <VsDataGridRow rowType={`header`}>
    <VsDataGridCell cellType={`columnheader`} gridColumn={1}>Test 1</VsDataGridCell>
    <VsDataGridCell cellType={`columnheader`} gridColumn={2}>Test 2</VsDataGridCell>
  </VsDataGridRow>

  <VsDataGridRow>
    <VsDataGridCell gridColumn={1}>Test</VsDataGridCell>
    <VsDataGridCell gridColumn={2}>Test</VsDataGridCell>
  </VsDataGridRow>
</VsDataGrid>
```

It renders as follows:

![image](https://user-images.githubusercontent.com/2900833/136915661-c29c7f51-7b91-4a35-82a5-a8a3f52e3d51.png)

The HTML looks as follows:

![image](https://user-images.githubusercontent.com/2900833/136916900-1b750136-5126-44ee-be3d-11f7037b8316.png)

The first-row element is automatically rendered by the component, can this be somehow removed? As it does not contain data and should be obsolete.

**Comment by hawkticehurst** [comment]
From the [data grid documentation](https://github.com/microsoft/vscode-webview-ui-toolkit/blob/main/src/data-grid/README.md#generate-header-attribute) (note the last bit):

> There are three values that can be passed to the attribute:
>
> `default`: A default header row will be automatically generated. This is the default value if the generate-header is not defined on the component.
> `sticky`: A sticky header row will be automatically generated.
> `none`: No header row will be generated.
>
> Important Note
>
> As shown above in the Basic Usage example, if the `vscode-data-grid` is defined using only HTML this attribute should be set to none and the header row should be manually created with HTML.

**Comment by hawkticehurst** [comment]
Hey @estruyf / @atanasster, circling back to this issue and seeing there are a ton of parallel conversations/ideas in this thread.

First, @estruyf, I want to see if the original issue posed in this thread feels like it's been resolved and this issue can be closed? Did the release of the toolkit React components help? Is there anything missing? 

I'll also call out that the [most recent toolkit release (`v.0.9.2`)](https://github.com/microsoft/vscode-webview-ui-toolkit/releases/tag/v0.9.2) included some small ergonomic improvements to data grid creation. Notably, data grids will default to having equally spaced column widths and manually defined grids no longer need to include `generate-header="none"`.

Second, of the parallel conversations that occurred in this thread, are there are any outstanding issues that you would like us to resolve still? If so, could you split them out into separate issues so that we can better track them?

Anything else I may have missed? Let me know!

**Comment by estruyf** [comment]
Thanks @hawkticehurst using it in one of my extensions and it works perfectly now! Thanks for the work. Feel free to close this one.

**Comment by hawkticehurst** [comment]
Yay, I'm thrilled to hear that! Thanks for letting me know! 😊
