### ISSUE TITLE
data-grid: cells are not aligned

### ISSUE THREAD

**Issue by atanasster** [microsoft/vscode-webview-ui-toolkit#276]
### Describe the bug

The datagrid cells are sometimes not aligned

### To reproduce
In the following example witness the `Type` column - rows `y` and `...props` 
```
<vscode-data-grid>
  <vscode-data-grid-row row-type="header">
    <vscode-data-grid-cell grid-column="1" cell-type="columnheader"> Name </vscode-data-grid-cell>
    <vscode-data-grid-cell grid-column="2" cell-type="columnheader"> Type </vscode-data-grid-cell>
    <vscode-data-grid-cell grid-column="3" cell-type="columnheader"> Parent </vscode-data-grid-cell>
    <vscode-data-grid-cell grid-column="4" cell-type="columnheader"> Value </vscode-data-grid-cell>
    <vscode-data-grid-cell grid-column="5" cell-type="columnheader">
      Description
    </vscode-data-grid-cell>
  </vscode-data-grid-row>
  <vscode-data-grid-row>
    <vscode-data-grid-cell grid-column="1">
      <a href="#">
        <code>y*</code>
      </a>
    </vscode-data-grid-cell>
    <vscode-data-grid-cell grid-column="2">
      <code>number</code>
    </vscode-data-grid-cell>
    <vscode-data-grid-cell grid-column="3">
      <a href="#">
        <code>CandlestickChartLineProps</code>
      </a> </vscode-data-grid-cell
    >\n<vscode-data-grid-cell grid-column="4">
      <code></code> </vscode-data-grid-cell
    >\n<vscode-data-grid-cell grid-column="5"> </vscode-data-grid-cell>
  </vscode-data-grid-row>
  <vscode-data-grid-row>
    <vscode-data-grid-cell grid-column="1">
      <code>...props</code>
    </vscode-data-grid-cell>
    <vscode-data-grid-cell grid-column="2">
        <code>LineProps</code>
    </vscode-data-grid-cell>
    <vscode-data-grid-cell grid-column="3"> </vscode-data-grid-cell>
    <vscode-data-grid-cell grid-column="4">
      <code></code>
    </vscode-data-grid-cell>
    <vscode-data-grid-cell grid-column="5"> </vscode-data-grid-cell>
  </vscode-data-grid-row>
</vscode-data-grid>
```

### Expected behavior

Expected all cells from the same column to be the same size

### Screenshots

![grab184](https://user-images.githubusercontent.com/6075606/138636103-b4f40f70-43c6-4821-8491-67d9b4e9be3f.jpg)

**Comment by hawkticehurst** [comment]
@atanasster I just opened a PR that resolves the original problem defined in this issue (i.e. setting better data grid column width defaults that should avoid this issue around incorrect cell alignment).

It does not, however, address some of your later comments about wanting columns to be auto-sized to the content. In the meantime, I think the solution is to manually define the `grid-template-columns` value to have custom widths when desired/necessary. 

For example, in your above example you could ensure the `description` column takes more space than other columns with the following: `grid-template-columns="1fr 1fr 1fr 1fr 3fr"`. By trying different values (maybe `4fr` is a better fit instead of `3fr`) you can find a set of spacing that feels right.

I think the idea of setting columns to be "auto-sized" to the content could potentially be worth exploring more but will probably be a lot trickier to get right in practice. For example, what's the "right" max-width for a column that has a huge multi-line block of text? I'd wager what feels "right" could get subjective really quickly depending on who you're asking.

So again in the meantime, it feels like a good compromise to have a default where columns take an equal amount of space and then let extension authors manually adjust that spacing if they desire.

With all that said, if auto-sized column widths are something that still feels important to you, you're more than welcome to open another issue and we can circle back to it after toolkit `v1.0` is released.

Let me know what you think! 😊

**Comment by atanasster** [comment]
@hawkticehurst thank you very much for the work, i already noticed the PR and am excited to try it out. Currently on a trip to Vegas and will give you feedback next week(ish) when I am back home.

For the columns, since my usage is dynamic (sometimes the jsdoc description for data types can be completely missing, and other times it can span multiple lines) - its a bit hard to fix the relative size of any of the columns. In the meantime i am indeed using some approximation for the most common use case using the 'grid-template-columns' as you suggest.

Thanks again
