### ISSUE TITLE
How to configure with React? (TS) (NextJS)

### ISSUE THREAD

**Issue by softmarshmallow** [microsoft/vscode-webview-ui-toolkit#296]
```tsx
import "@vscode/webview-ui-toolkit";
function EmptyState() {
  return <vscode-progress-ring></vscode-progress-ring>;
}
```

will throw
`Property 'vscode-progress-ring' does not exist on type 'JSX.IntrinsicElements'.ts(2339)`

Is there extra steps required to setup?

**Comment by atanasster** [comment]
@softmarshmallow you just need to enhance the `JSX` namespace. I usually create a `typings.d.ts` file with something like that:
```
declare namespace JSX {
  interface IntrinsicElements {
    'vscode-data-grid': any;
    'vscode-data-grid-row': any;
    'vscode-data-grid-cell': any;
    'vscode-progress-ring': any;
  }
}
```

**Comment by softmarshmallow** [comment]
Thanks. nooby question it was 🤣

**Comment by atanasster** [comment]
I believe they will be more appropriate to include in the react version of the components, no? The authors are working on this afaics, so its just a small snag until its available.

**Comment by hawkticehurst** [comment]
Thanks for chiming in with the quick answer @atanasster!!

Also no no, @softmarshmallow, not nooby at all! 

In fact, it's incredibly helpful to me since I'm currently working on a React sample extension/docs and this sounds like it's a topic that should be discussed (and ideally addressed out of the box) so that others don't run into the same issue as you. Thank you for sharing! 🙂

**Comment by hawkticehurst** [comment]
> I believe they will be more appropriate to include in the react version of the components, no? The authors are working on this afaics, so its just a small snag until its available.

Yeah, currently we're working on a React sample extension and corresponding documentation (versus a full-blown React implementation of the toolkit). 

But if there's any way to include better type declarations as part of the sample or documentation or even packaged and published as part of the toolkit I'll find some way of making it clear how to accomplish better typing in React + toolkit extensions.

**Comment by hawkticehurst** [comment]
> Thank you for sharing! 🙂

Also on this note, @softmarshmallow if there are any other issues, points of confusion, needed/wanted improvements while using the toolkit please do continue to open issues!

**Comment by atanasster** [comment]
@hawkticehurst I moved my extension back to react in anticipation of the react support. In the next days, I will also need to use the `tree-view` component. For now, with just a simple react wrapper, but do you have eta?

**Comment by softmarshmallow** [comment]
![image](https://user-images.githubusercontent.com/16307013/141267771-b02ac044-fd24-4b44-a738-8c18208f25d4.png)

Probably mis config or ts-server problem, but here is the case that it still won't work with explicit declaration.

Sharing so that others can know.

**Comment by softmarshmallow** [comment]
Changing
from
```ts
declare namespace JSX {
  interface IntrinsicElements {
    'vscode-progress-ring': any;
  }
}
```

to

```ts
declare global {
  namespace JSX {
    interface IntrinsicElements {
      "vscode-progress-ring": any;
    }
  }
}
```

did the trick

**Comment by hawkticehurst** [comment]
> @hawkticehurst I moved my extension back to react in anticipation of the react support. In the next days, I will also need to use the `tree-view` component. For now, with just a simple react wrapper, but do you have eta?

@atanasster The react sample extension/docs work has been a bit slow going due to a couple of different blockers/hiccups this week, so while I had hoped to have the first draft of this work done by the of this week it's looking like that will probably happen towards the end of next week. 

Once that draft is ready I'd be happy to share a link to the development branch so you (and anyone else) can take an early peek at it if that would be helpful. 

Also after that draft is finished, I expect there to be a few rounds of editing since the plan is to have this extension/docs act as the model/template for future frontend framework sample extensions/docs and I want to make sure we get those details correct now.

So long story long, this work is probably 2 weeks out at the very minimum.

**Comment by hawkticehurst** [comment]
> In the next days, I will also need to use the `tree-view` component.

Oh, also did you mean to say `tree-view` component here? 

We don't currently have a `tree-view` component in the toolkit or any plans to make one in the future, since the [TreeView API](https://code.visualstudio.com/api/extension-guides/tree-view) already exists as part of the core VS Code extension API. So if you do in fact need a tree view there should be nothing stopping you from using it now 🙂.

**Comment by atanasster** [comment]
@hawkticehurst , maybe I am missing something - but how can I use the TreeView API in a webview?

**Comment by hawkticehurst** [comment]
@atanasster Whoops totally missed this message until now.

Also, oh yeah, sorry if that wasn't super clear. No, you're not missing anything, the TreeView API cannot be used inside a webview. 

With that said, I totally realized I forgot to ask you what you're trying to use a tree view for in your webview? (Or more accurately, I thought you had already added your thoughts to [this issue](https://github.com/microsoft/vscode-webview-ui-toolkit/issues/255), but I guess I was mistaken.)

To give some background, we have gotten requests for a tree view a few times at this point and are currently trying to collect as much feedback as possible about what people are hoping to use a tree view for to get a better picture of whether the work of creating a toolkit version of the component is worth it in the long run. 

We are hesitant to duplicate component work, especially when a more performant native version of the API exists that, while not usable inside a webview, can still often be used in a hybrid fashion alongside webviews as demonstrated in the [notepad sample extension](https://github.com/microsoft/vscode-webview-ui-toolkit-samples/tree/main/notepad).

But again hearing about your needs and use cases for a tree view that lives inside a webview would be very helpful!

**Comment by atanasster** [comment]
@hawkticehurst , sorry I had missed that other conversation, and will add my use-case and comments there

**Comment by hawkticehurst** [comment]
No worries at all! Twas an easy issue to miss.

But yes, adding your thoughts/uses cases in that thread would be greatly appreciated! Thank you 🙂
