### ISSUE TITLE
vscode-dropdown does not respect empty option values

### ISSUE THREAD

**Issue by WebFreak001** [microsoft/vscode-webview-ui-toolkit#327]
### Describe the bug

When having a dropdown with an option with value set to the empty string, the empty value is not used, but the label of the option instead.

### To reproduce

```html
Test:
<vscode-dropdown id="testin">
	<vscode-option value="">Foo</vscode-option>
	<vscode-option value="val2">Bar</vscode-option>
</vscode-dropdown>
value:
<p id="testout"></p>
<script>
	var testin = document.getElementById("testin");
	var testout = document.getElementById("testout");
	testin.oninput = function() {
		testout.textContent = testin.value;
	};
</script>
```

### Expected behavior

`testin.value` should be `""` when selecting `Foo`, as this is how the HTML select dropdown behaves, but it's actually `"Foo"`.

### Desktop (please complete the following information):

-   OS Version: VSCode 1.63.2 on Electron 13.6.8 on ArchLinux i3 (X11)
-   Toolkit Version: `v0.8.5`

**Comment by hawkticehurst** [comment]
Hey @WebFreak001, thanks for the heads up! I did some testing of my own and can confirm the issue!

In this case, since the toolkit doesn't do anything to alter the `value` attribute behavior of the `option` component provided by FAST (the framework we use to build the toolkit) this is actually going to be an upstream issue that they will have to fix.

I'm happy to open this issue with FAST on your behalf and also leave this issue open in the meantime to make sure it's tracked on the toolkit side.

Let me know if you have questions/concerns!

**Comment by hawkticehurst** [comment]
@WebFreak001 looks like FAST had a really quick turnaround on fixing this issue! 

If I recall correctly, they publish new package updates via a nightly build so we should have this change merged into the toolkit by tomorrow 👍
