### ISSUE TITLE
Notes sample with CustomEditor API

### ISSUE THREAD

**Issue by rangav** [microsoft/vscode-webview-ui-toolkit#337]
### Feature/component description

Can you provide notes example with CustomEditor API like below one

https://github.com/microsoft/vscode-webview-ui-toolkit-samples/tree/main/default/notepad

### Use case

I am creator of [Thunder Client](https://marketplace.visualstudio.com/items?itemName=rangav.vscode-thunder-client) extension, I can't find example how to use CustomEditor api with virtual document similar to Notes app

I want to use the following functionality in my extension

- show alert when user is trying to close webview without saving? like in default editor
- Italic title option for readonly mode like in editor
- Dirty Indicator (black dot beside title) for unsaved mode like in default editor

**Comment by rangav** [comment]
related https://github.com/microsoft/vscode-extension-samples/issues/477

**Comment by hawkticehurst** [comment]
Hey @rangav, thanks for filing this sample request! 

With that said, would you mind closing and moving this issue to our [sample extension repo](https://github.com/microsoft/vscode-webview-ui-toolkit-samples/issues) since that's where we track all our sample related work and I don't want this to get lost amongst other toolkit issues?

**Comment by rangav** [comment]
Hi @hawkticehurst sure

moved to samples https://github.com/microsoft/vscode-webview-ui-toolkit-samples/issues/60

**Comment by hawkticehurst** [comment]
Awesome, thanks so much for doing that!
