### ISSUE TITLE
Reuse VS Code browser/ui toolkit

### ISSUE THREAD

**Issue by gar1t** [microsoft/vscode-webview-ui-toolkit#341]
### Feature/component description

VS Code itself has a full set of UI components (see vscode/src/vs/base/browser/ui). Rather than duplicate (much of?) this facility in a separate library, why not enable its reuse for custom extensions? Is there a way to do this, short of packaging the upstream source myself?

### Use case

I'm creating various VS extensions and want a UI for building something that cleanly integrates with VS Code without re-inventing everything in a separate library.

**Comment by daviddossett** [comment]
Hey @gar1t, thanks for asking. Technically this is probably possible, but it isn't trivial, and such an effort would need considerable support from the VS Code core engineering team. The team is quite small and has limited bandwidth—they aren't in a position to investigate this and groom/restructure those components to be ready for reuse in a formal component library given everything else they are juggling.

I'd suggest filing an issue on the main VS Code repo if you have more thoughts on use cases or possible implementations if you've done some digging already. Always good to have more input for future decisions!

**Comment by hawkticehurst** [comment]
I'm going to close this issue now as (after some explorations) it seems very unlikely that this will be possible in the foreseeable future

I love this idea and have done a handful of explorations during the last few months on the possibility of exposing core VS Code UI components/APIs as webview toolkit components but it has indeed proven to be **_exceedingly_** hard to achieve

Like David suggested, it would realistically require a mountain of effort/coordination between both the core VS Code engineers and those working on the toolkit –– something that is unlikely to happen since we're both small teams with very limited bandwidth at this time
