### ISSUE TITLE
Add multi-select dropdown component

### ISSUE THREAD

**Issue by pwang347** [microsoft/vscode-webview-ui-toolkit#352]
### Feature request

Firstly, thanks for the great work in this project! It would be great to have a multi-select dropdown component (possibly exposed as an option for the existing dropdown). 

### Expected behavior

* Each dropdown item would have an indicator of whether it is selected or not (e.g. a checkbox)
* Clicking an item would not dismiss the dropdown menu, but would instead toggle that status
* The menu could be dismissable via ESC or moving focus away from the menu

The displayed text could be a comma-separated list that is truncated with ellipses.

### Use case

Currently there's no control to select multiple items.

### Screenshots/references

As an example, here is a similar control in fluent UI:
![image](https://user-images.githubusercontent.com/8560030/158491161-476ef26a-3f8d-4514-9a2c-8e3d5e0dccfe.png)

Thanks!

**Comment by hawkticehurst** [comment]
Hey Paul! Thanks for the component suggestion! Happy to hear it sounds like your experience with the toolkit has gone smoothly thus far.

I'd certainly be open to discussing the inclusion of a multi-select dropdown. It might end up a bit of a long pull to get something like this into the toolkit because I don't believe anything like this exists in `fast-foundation` at this time and thus might take more effort to adapt to the current dropdown or create from scratch? (@chrisdholt keep me honest on this one).

With all this said, just to cover the most obvious solution is there a reason that a regular list of checkboxes doesn't work for your use case? 

If space is the concern (i.e. you have a really long list), would wrapping the checkbox list in a container element (i.e. `section` HTML tag) and applying `overflow-y: scroll` and setting a max-height work for you? You could even add some nice styles (i.e. border, etc) to the container element to give it a sort of listbox appearance.

**Comment by hawkticehurst** [comment]
Also cc @daviddossett for any design input/thoughts on this type of scenario/proposed component

**Comment by pwang347** [comment]
> Hey Paul! Thanks for the component suggestion! Happy to hear it sounds like your experience with the toolkit has gone smoothly thus far.
> 
> I'd certainly be open to discussing the inclusion of a multi-select dropdown. It might end up a bit of a long pull to get something like this into the toolkit, however, because I don't believe anything like this exists in `fast-foundation` at this time and thus might take more effort to adapt to the current dropdown or create from scratch? (@chrisdholt keep me honest on this one).
> 
> With all this said, just to cover the most obvious solution, if all you need to do is select multiple options from a list, is there a reason that a regular list of checkboxes doesn't work for your use case?
> 
> If space is the concern (i.e. you have a really long list), would wrapping the checkbox list in a container element (i.e. `section` HTML tag) and applying `overflow-y: scroll` and setting a max-height work for you? You could even add some nice styles (i.e. border, etc) to the container element to give it a sort of listbox appearance.

That makes sense, also appreciate the suggestions!

Yes, vertical space is a concern here since we'll expect to see somewhere around 10-20 items typically and have some additional controls beneath it. A max-height listbox could definitely work and gives us further flexibility to customize, e.g. adding some sort of sticky header for item grouping.

I guess my only two worries are that it might be a bit hard to get a visual summary of the selection state given only the list box and without doing more complicated custom work, and generally that we'd like to align to existing control paradigms as much as possible (to feel native and cohesive).

Cool to know that the above concept is already in PR though! Will keep an eye out for that, and maybe try something similar for a stopgap solution.

Thanks!

**Comment by hawkticehurst** [comment]
> I guess my only two worries are that it might be a bit hard to get a visual summary of the selection state given only the list box and without doing more complicated custom work, and generally that we'd like to align to existing control paradigms as much as possible (to feel native and cohesive).

Yeah, the visual summary of selected items would definitely take more effort but, depending on what you want to do, I'd wager it wouldn't be too hard actually. For example, I bet the comma-separated list idea you mentioned in the original comment could be achieved in a couple of lines of JS/TS. Something like so (give or take a few details) could probably get you pretty far:

```js
// Rerun this function every time checklist state changes (via "click" or "change" events) and 
// add the returned string to the DOM
function getSummaryString() {
  const checkedItems = document.querySelectorAll("#checklist-container > vscode-checkbox:checked");
  let summary = "";
  
  for (const checkbox of checkedItems) {
    summary += `${checkbox.value} ,`;
  }
  
  // Remove trailing comma from the summary string if desired

  return summary;
}
```

With all that said, I definitely understand the desire to make sure all of this aligns with existing paradigms. 

I think the primary paradigm for handling multi-selection is just a really long list of checkboxes (a la the settings page in VS Code) and I'm not too sure about how (or even if) we show visual summaries of multiple selected options/choices. If anything, I'll defer to @daviddossett (or even @misolori) on this topic since I think they will have a broader knowledge than I do.

**Comment by daviddossett** [comment]
FWIW I don't believe there are multi-select dropdowns in VS Code.

**Comment by daviddossett** [comment]
@pwang347 Assuming this is for the DW extension, I can send you a note tomorrow about ways to get around this.

**Comment by hawkticehurst** [comment]
Going back through old issues. Was your issue resolved @pwang347 or is a multi-select dropdown component something you're still requesting?

**Comment by chrisdholt** [comment]
> Going back through old issues. Was your issue resolved @pwang347 or is a multi-select dropdown component something you're still requesting?

FYI - multiselect mode went in (yesterday?) to fast-foundation. Should be supported on listbox AND select :).

**Comment by hawkticehurst** [comment]
Oh nice, thanks for the heads up @chrisdholt!

**Comment by daviddossett** [comment]
Closing this since we aren't likely to introduce a multi-select dropdown as long as it isn't available in VS Code core 👍 Definitely recommend the multi-select quick input as an alternative!


https://code.visualstudio.com/api/ux-guidelines/quick-picks#multiple-selections
https://code.visualstudio.com/api/references/vscode-api#QuickPick (see `canSelectMany`)
