### ISSUE TITLE
`.vscode-test-web` folder is published to npm

### ISSUE THREAD

**Issue by F3n67u** [microsoft/vscode-webview-ui-toolkit#356]
### Describe the bug

a 23M `.vscode-test-web` dir is published to npm, make `vscode-webview-ui-toolkit`'s unpack size huge(24.3M current)

https://unpkg.com/browse/@vscode/webview-ui-toolkit@0.9.2/

<img width="1016" alt="image" src="https://user-images.githubusercontent.com/12343178/159617875-12cac90d-fb04-4307-9142-62ac7f2197b1.png">

### To reproduce

```
$ mkdir toolkit-test 
$ cd toolkit-test
$ yarn add @vscode/webview-ui-toolkit 
$ cd node_modules/@vscode/webview-ui-toolkit
$ du -sh .vscode-test-web 
 23M    .vscode-test-web
```

### Expected behavior

`.vscode-test-web `is ignored when published to npm

### Current behavior

`.vscode-test-web` dir is published to npm

### BTW

should we also ignore `react` dir?

**Comment by hawkticehurst** [comment]
Wowow 😅🤦🏻‍♂️ thank you so much for catching this (and for the subsequent PR)!

I'll go ahead and merge that right now and publish a new patched version of the package.

Also, no the `react` folder in the root directory should stay. It's the (annoyingly janky) way that we have to structure the NPM build at this time so that toolkit users can import the toolkit React components via the `@vscode/webview-ui-toolkit/react` path.

It will eventually be removed/restructured once TypeScript releases support for the package.json `exports` field. You can [read more about it here](https://github.com/microsoft/vscode-webview-ui-toolkit/blob/main/scripts/move-react-build-dir.js#L8-L41) if you're curious.
