### ISSUE TITLE
Option to add style to a placeholder of vscode-text-field

### ISSUE THREAD

**Issue by NetaMolcho** [microsoft/vscode-webview-ui-toolkit#376]
### Feature request

First I really want to thank you for an amazing job.
And I would love to hear if there is an option of adding style to the placeholder of the vscode-text-field object.
I'm just trying to get placeholder to be 'font-style: italic' but without success.

### Expected behavior

To make only the placeholder be in 'font-style: italic', without what is written in the input of the vscode-text-field

### Current behavior

I currently have not found a way to do that

### Screenshots/references

![image](https://user-images.githubusercontent.com/35297731/174434620-ff837212-a609-46ef-88ea-2bbe8b086e4a.png)

Thank you!

**Comment by daviddossett** [comment]
@NetaMolcho is this something you've seen in VS Code before? Generally speaking we intentionally limit the components to ensure the components look and feel like the "native" VS Code components.

**Comment by NetaMolcho** [comment]
@evangrayk thank you so much, it works well 🙏

**Comment by hawkticehurst** [comment]
Hey all! Quickly chiming in on this.

> One thing that's possible but not documented very well IMO is that you can use CSS to select inside the shadow root to apply styles

Haha yeahhh, this is an admittedly very weird part of the Webview UI Toolkit story right now.

We have _intentionally_ not been documenting component parts because while they totally work for what @NetaMolcho is hoping to achieve, we would prefer if they weren't used at this time 😅. Let me explain...

The toolkit is built with another Microsoft technology called FAST (a framework for building web components). Part of what they offer (and what we use) is a set of unstyled base-components. This means FAST implements the underlying template (aka HTML) and behavior of each component and then we can (mostly) focus on styling the components.

The issue with this model is that it means we don't have any control over the underlying templates and therefore the element parts that get exposed to you all.

Why does this matter? One of the primary reasons that the toolkit exists is to provide a set of components that strictly adhere to the VS Code design language. We care about this because we want extensions to look and feel like the rest of VS Code so there is a seamless UX experience between using native/core VS Code UI and extension UI.

_^ This is what @daviddossett was trying to get at in his original comment. Native VS Code text fields don't have italicized placeholder text so we would want to make sure extension text fields don't have them either._

For the time being our only solution has been to not document these realities and hope that most people won't notice, but this will likely change in the future. FAST currently has plans of building new APIs that will give full control of the underlying component templates.

If I recall correctly, those changes are going to take a while to land, but when they do we will likely adopt them so we can add/remove the element parts that make sense for the toolkit/VS Code design language and finally be able to document them properly.

Of course, you're fully capable of using these component parts in the meantime -- I can't stop you 😉. But in general, we would strongly prefer and appreciate it if extension authors do not change the styles of the toolkit components if it means the components would not align with native VS Code UI.

Hope that all makes sense and more than happy to answer any questions if you have them 😊.

**Comment by daviddossett** [comment]
Echoing the answer above—we recommend against styling the toolkit components that are intended to always be in alignment with the VS Code UI. However, as pointed out, there is a back door if you really need to do something for your use case.
