### ISSUE TITLE
Not able to stylize individual cells in a vscode-data-grid

### ISSUE THREAD

**Issue by jeffb-sfdc** [microsoft/vscode-webview-ui-toolkit#378]
### Describe the bug
I'm attempting to stylize individual cells in a vscode-data-grid, however the text is being HTML escaped.  Is it possible to set a cell to stylized HTML?  Or to go back and set the CSS of a cell once the cell has been created?

### To reproduce

I'm creating a grid ala:
```
                  <vscode-data-grid
                    class='my-data-grid'
                    grid-template-columns='240px 320px 200px 200px'
                  >
                  </vscode-data-grid>
```

...and then setting the data like so:
```
                  const myDataGrid = document.querySelector('.my-data-grid');
                  myDataGrid.columnDefinitions = [
                    { columnDataKey: 'columnKey0', title: 'A' },
                    { columnDataKey: 'columnKey1', title: 'B' },
                    { columnDataKey: 'columnKey2', title: 'C' },
                    { columnDataKey: 'columnKey3', title: 'D' }
                  ];

                  const myRowsData = [];
                  myData.forEach(data => {
                    const connectedStatus = (data.connectedStatus === 'Connected')
                      ? '<span style="green">Connected</span>'
                      : '<span style="red">Not Connected</span>';
                    nonScratchOrgsRowsData.push({
                      columnKey0: data.a,
                      columnKey1: data.b,
                      columnKey2: data.c,
                      columnKey3: connectedStatus
                    });
                  });
                  myDataGrid.rowsData = myRowsData;
```

### Expected behavior

I'd like the text in column 3 to be stylized.

### Current behavior

The HTML (the spans) are not stylized and instead of `Connected` appearing, `<span style="green">Connected</span>` appears.

### Additional context

I tried to keep this issue short & sweet.  If you need any more info on this issue, just let me know.

Also, I didn't see anything in the vscode-data-grid README (https://github.com/microsoft/vscode-webview-ui-toolkit/blob/main/src/data-grid/README.md) on styling, and I didn't notice a means to edit the styling in the interactive story book either (https://microsoft.github.io/vscode-webview-ui-toolkit/?path=/story/library-data-grid--default&args=gridTemplateColumns:foo;hasCustomTitles:true).

**Comment by jeffb-sfdc** [comment]
I should also mention that I set a break point, and after
```
myDataGrid.rowsData = myRowsData;
```
...is called, I tried to manually set the color, like so:
```
myDataGrid.rowsData[0].columnKey3.fontcolor = "red"
myDataGrid.rowsData[1].columnKey3.fontcolor = "#FF0000"
myDataGrid.rowsData[2].columnKey3.fontcolor = "FF0000"
```
...but none of these set the color to red

**Comment by hawkticehurst** [comment]
Hey @jeffb-sfdc! Thanks for the issue!

I started looking into this today but probably won't have a fully informed answer until next week. 

But just wanted to give a status update before the weekend starts that I've seen the issue and am looking into it.

Thanks for your patience 😄

**Comment by jeffb-sfdc** [comment]
Thanks, and no worries!

**Comment by hawkticehurst** [comment]
Alright, I have some updates!

## ❌ Add stylized HTML

To answer the initial question, no I don't believe you will be able to add stylized HTML to the data grid because it will always be escaped (as you discovered)--this is done for security purposes.

## ❌ Go back and set cell styles after creation

This _should_ be possible, however, no matter what I try I keep running into a weird issue where a query selector for all the vscode cell elements only returns the first row of cells for some reason and results in a partially working solution. I've added a much longer explanation if you're curious.

<details>
<summary>View longer explanation</summary>

For context setting, here's the JS that populates the data grid with titles/data (note the fact that I'm filling in the last column with connected status text for this explaination):

```js
const basicGrid = document.querySelector(".my-data-grid");
basicGrid.columnDefinitions = [
  { columnDataKey: 'columnKey0', title: 'A' },
  { columnDataKey: 'columnKey1', title: 'B' },
  { columnDataKey: 'columnKey2', title: 'C' },
  { columnDataKey: 'columnKey3', title: 'D' }
];
basicGrid.rowsData = [
  { columnKey0: "Cell Data", columnKey1: "Cell Data", columnKey2: "Cell Data", columnKey3: "Connected" },
  { columnKey0: "Cell Data", columnKey1: "Cell Data", columnKey2: "Cell Data", columnKey3: "Connected" },
  { columnKey0: "Cell Data", columnKey1: "Cell Data", columnKey2: "Cell Data", columnKey3: "Disconnected" },
];
```

At this point, it should be possible to use `document.querySelectorAll` to get a reference to every cell in the above data grid. The problem I'm running into however is that the first row of cells is returned **but not the others**. _I think_ this might be caused by how web components/the shadow dom handle slotted children, but I've had no luck finding any answers to why this is happening at this point.

```js
// WARNING: THIS CODE DOES NOT WORK!!

// BROKEN PART: Get an array of all the cells in the basic grid only returns the first row 😪
const cells = document.querySelectorAll(`#basic-grid vscode-data-grid-cell`);
// Note: Could refine the above selector even further by only getting the cells which are in column 4 which should improve performance a bit
// const cells = document.querySelectorAll(`#basic-grid vscode-data-grid-cell[grid-column="4"]`);
for (const cell of cells) {
  switch (cell.textContent) {
    case 'Connected':
      cell.style.color = 'green';
      break;
    case 'Disconnected':
      cell.style.color = 'red';
      break;
    default:
      // Do nothing to cells that are not related to connection status
      break;
  }
}
```

We can still at least confirm that the above code works in theory by going back and adjusting the header row to have either "Connected" or "Disconnected" text content in the cells and testing the extension.

```js
basicGrid.columnDefinitions = [
  { columnDataKey: 'columnKey0', title: 'A' },
  { columnDataKey: 'columnKey1', title: 'B' },
  { columnDataKey: 'columnKey2', title: 'C' },
  { columnDataKey: 'columnKey3', title: 'Connected' } // <-- temporarily changed to show that the above code technically works
];
```

Here's a screenshot:

<img width="768" alt="vscode-connected" src="https://user-images.githubusercontent.com/39639992/176050697-3ba39e95-8781-45ad-90b5-4be053aab727.png">

</details>

## ✅ Dynamically generate data grid

This solution entails using JS DOM APIs to dynamically generate the data grid row and cell elements and is actually what most extensions will do when using a framework like React since it's not as easy to use the `rowsData` API in that context (although the DOM APIs are, of course, abstracted away from devs and they will use the framework syntax instead).

I also think this solution is actually the best of both worlds in your case because it means you will be conditionally adding styles to the relevant cells _while_ the data grid is being created (versus adding styles after the data grid has been created)--aka yay for slightly improved performance by effectively not iterating through the data grid twice.

<details>
<summary>Working solution/code snippet</summary>

Here's the full solution!

```js
window.addEventListener("load", main);

function main() {
  const headerData = ['A', 'B', 'C', 'D'];
  const rowsData = [
    ["Column 1 Data", "Column 2 Data", "Column 3 Data", "Connected"],
    ["Column 1 Data", "Column 2 Data", "Column 3 Data", "Disconnected"],
    ["Column 1 Data", "Column 2 Data", "Column 3 Data", "Connected"],
  ];

  const basicGrid = document.querySelector(".my-data-grid");
  
  // Create and append header row
  const headerRow = createHeaderRow();
  console.log(headerRow);
  for (const [index, data] of headerData.entries()) {
    const cell = createHeaderCell(index, data);
    headerRow.appendChild(cell);
  }
  basicGrid.appendChild(headerRow);

  // Create and append other rows
  for (const rowData of rowsData) {
    const row = createRow();
    for (const [index, data] of rowData.entries()) {
      const cell = createCell(index, data);
      switch (data) {
        case 'Connected':
          cell.style.color = 'green';
          break;
        case 'Disconnected':
          cell.style.color = 'red';
          break;
        default:
          // Do nothing to cells that are not related to connection status
          break;
      }
      row.appendChild(cell);
    }
    basicGrid.appendChild(row);
  }
}

function createRow() {
  return document.createElement('vscode-data-grid-row');
}

function createHeaderRow() {
  const row = createRow();
  row.setAttribute('row-type', 'header');
  return row;
}

function createCell(index, data) {
  const cell = document.createElement('vscode-data-grid-cell');
  cell.setAttribute('grid-column', index + 1);
  cell.textContent = data;
  return cell;
}

function createHeaderCell(index, data) {
  const cell = createCell(index, data);
  cell.setAttribute('cell-type', 'columnheader');
  return cell;
}
```
</details>

<details>
<summary>Explaination of solution/code snippet</summary>
To start, use these four helper functions for creating data grid rows and cells using DOM APIs.

```js
function createRow() {
  return document.createElement('vscode-data-grid-row');
}

function createHeaderRow() {
  const row = createRow();
  row.setAttribute('row-type', 'header');
  return row;
}

function createCell(index, data) {
  const cell = document.createElement('vscode-data-grid-cell');
  cell.setAttribute('grid-column', index + 1);
  cell.textContent = data;
  return cell;
}

function createHeaderCell(index, data) {
  const cell = createCell(index, data);
  cell.setAttribute('cell-type', 'columnheader');
  return cell;
}
```

I've also created some fake data to demo this in the form of an array for header data and a 2D array for rows data. This decision has implications for how I implemented everything else that will follow but this implementation should be more than flexible to be remixed and adapted if you decide you want your data to be in a different structure.

```js
const headerData = ['A', 'B', 'C', 'D'];
const rowsData = [
  ["Column 1 Data", "Column 2 Data", "Column 3 Data", "Connected"],
  ["Column 1 Data", "Column 2 Data", "Column 3 Data", "Disconnected"],
  ["Column 1 Data", "Column 2 Data", "Column 3 Data", "Connected"],
];
```

As usual, get a reference to the `vscode-data-grid` component defined in HTML.

```js
const basicGrid = document.querySelector(".my-data-grid");
```

Creating and appending the header row using the `headerData` is a fairly straightforward case of using the above helper functions and DOM APIs.

```js
// Create and append header row
const headerRow = createHeaderRow();
for (const [index, data] of headerData.entries()) {
  const cell = createHeaderCell(index, data);
  headerRow.appendChild(cell);
}
basicGrid.appendChild(headerRow);
```

Finally creating the rest of the rows/cells is another case of using helper functions and DOM APIs. This is also where the logic for conditionally adding cell styles can be added.

```js
// Create and append other rows
for (const rowData of rowsData) {
  const row = createRow();
  for (const [index, data] of rowData.entries()) {
    const cell = createCell(index, data);
    switch (data) {
      case 'Connected':
        cell.style.color = 'green';
        break;
      case 'Disconnected':
        cell.style.color = 'red';
        break;
      default:
        // Do nothing to cells that are not related to connection status
        break;
    }
    row.appendChild(cell);
  }
  basicGrid.appendChild(row);
}
```

And voila, it works 🥳

<img width="768" alt="vscode-connected-success" src="https://user-images.githubusercontent.com/39639992/176055920-a3e489f4-685c-49ed-ab50-0fa48f7360fe.png">
</details>

Let me know if you have any questions and if this solution helps resolve your problem!

**Comment by jeffb-sfdc** [comment]
Thanks for the update @hawkticehurst 

> no I don't believe you will be able to add stylized HTML to the data grid because it will always be escaped

I figured as much.  Years ago I used ASP.NET MVC, and the Razor view engine defaulted to escaping HTML, but there were APIs that allowed you to override and send raw unescaped HTML.  It would be nice if there was a means to do this.

> ...I've added a much longer explanation if you're curious.

Absolutely!

(OK, I read through the details)

We kind of have a working fix, but it's really hacky, and probably pretty brittle and likely to break.

1. In our panel's .ts file we have a `_getWebviewContent()` which basically returns static HTML and it has a `<vscode-data-grid>` in it.
2. Within the HTML, we have a `<script>` block and via a custom event the data is passed and then the rows and columns are generated
3. We then have a `setTimeout()` of 250ms, and update the cells via this (more or less):
```
setTimeout(() => {
                    document.querySelectorAll('.my-data-grid [grid-column="5"]').forEach(el => {
                      if (el.textContent === 'Connected') {
                        el.classList.add('connected-text');
                      }
                    });
                  }, 250);
                  break;
              }
```

So, we have a workaround, but it's not great.

OK, there seems to be a few bugs here:
1. setting the color via `cell.style.color` is not working
2. setting the color via `myDataGrid.rowsData[0].columnKey1.fontcolor` is not working
3. The query selector retuning elements, but only of the first row (which you are seeing) not working.

How do you want to handle this ticket?  Keep it open with the bug label attached?

**Comment by hawkticehurst** [comment]
You're welcome!

> but there were APIs that allowed you to override and send raw unescaped HTML. It would be nice if there was a means to do this.

Unfortunately, something like this is out of our control at this point because we use a set of unstyled base components from another Microsoft project called FAST to implement all our components. With that said, I know their programming model/API is going to be changing a lot in the coming months/years to a point where we on the toolkit side will eventually have full control over the implementation details of the base components. So this could potentially be revisited later!

> ...I've added a much longer explanation if you're curious.
Absolutely!

Just to double check, did you see that the content is already there but is just hidden in a `<details>` tag?

If you click on these three items marked by red arrows they can be expanded to see more content:

<img width="619" alt="github-details-closed" src="https://user-images.githubusercontent.com/39639992/176776034-b2194d03-5656-45d8-aaf8-7cbd9de40a15.png">

<img width="620" alt="github-details-open" src="https://user-images.githubusercontent.com/39639992/176776054-220d6329-4335-4e4c-9eb7-610fc96d1945.png">

> We then have a setTimeout() of 250ms, and update the cells via this (more or less)

I assume you're setting a timeout to make sure that the `rowsData` API has enough time to finish generating the data grid? 

If so, let me know what your thoughts are on the solution where you generate the data grid using DOM APIs (read the content that is hidden in the collapsed details tag if you haven't already) -- if you go with that method then you should be able to simply skip this timeout code entirely and just add the `connected-text` class while the data grid is being created versus afterwards?

> setting the color via `cell.style.color` is not working

In what context is it not working? With your current solution or one of the solutions I wrote out?

> setting the color via `myDataGrid.rowsData[0].columnKey1.fontcolor` is not working

I'd have to double check but I don't think this would ever work because I'm pretty sure `myDataGrid.rowsData[0].columnKey1` returns a reference to your data, not a reference to the DOM element that contains the data. I think that call basically amounts to `"some string of data".fontcolor` which isn't a valid API call.

> The query selector retuning elements, but only of the first row (which you are seeing) not working.

Yeah this one is still so weird.. that's why I suggested you go with the explanation given in the third third option because I'm still not sure why the first row is being returned right now

**Comment by hawkticehurst** [comment]
Hey @jeffb-sfdc, checking back in to see if you were able to resolve this issue or have any more questions?

**Comment by jeffb-sfdc** [comment]
I think we're good, thanks @hawkticehurst

**Comment by hawkticehurst** [comment]
Great! Happy to hear it. Feel free to open another issue if you ever run into more issues/questions!
