### ISSUE TITLE
Panel Selection Changed Event

### ISSUE THREAD

**Issue by necatiarslan** [microsoft/vscode-webview-ui-toolkit#396]
Hi,
Does the Panel component have a Selection Changed event?

I want to add an event listener and save the active panel so that when the HTML is rendered, panel control will be on the same tab.
If not, how can I stay on the same tab after an HTML render?

**Comment by hawkticehurst** [comment]
Hey @necatiarslan,

The `panels` component does have a custom `changed` event that will fire when a tab is clicked or during keyboard navigation.

Here's a code snippet to get you started in that direction:

```html
<vscode-panels id="basic-panels">
  <!-- ... vscode-panel-tab and vscode-panel-view markup ... -->
</vscode-panels>
```

```js
const basicPanels = document.getElementById("basic-panels");
basicPanels.addEventListener("change", (e) => {
  console.log("tab changed!");
  console.log(e.target); // this will log a reference to the `basic-panels` DOM node
});
```

With that said, could you explain a bit more of what your goal is about staying on the same tab and what you mean by "HTML render"?

I ask because if you're trying to get a specific tab to be opened whenever your webview gets rendered there's an attribute called `activeid` which might be better suited for your needs.

Here's a [reference to the docs](https://github.com/microsoft/vscode-webview-ui-toolkit/blob/main/src/panels/README.md#active-id-attribute).

Let me know if either of these solutions helps and if you have any more questions!

**Comment by hawkticehurst** [comment]
Hey @necatiarslan I'm circling back to see if any of these suggestions resolved your issue? Do you have any other questions or can we close this issue?

**Comment by necatiarslan** [comment]
solved

**Comment by hawkticehurst** [comment]
Perfect, glad to hear it, and thanks for updating the issue!
