### ISSUE TITLE
[Feature Request] way to show icon buttons inside VSCodeTextField

### ISSUE THREAD

**Issue by jedwards1211** [microsoft/vscode-webview-ui-toolkit#424]
### Feature request

I want to be able to put icon buttons inside a `VSCodeTextField` like in the builtin Search view.

### Use case

I'm trying to mimic most of the Search view UI for an AST search and replace extension I'm making.
### Screenshots/references

<img width="399" alt="image" src="https://user-images.githubusercontent.com/1448194/205505756-a78899b2-d1f1-4f20-af1c-d03027bba85f.png">

**Comment by hawkticehurst** [comment]
Hey @jedwards1211! 

If I'm understanding your request correctly, I've actually [already (partially) answered this in a previous issue](https://github.com/microsoft/vscode-webview-ui-toolkit/issues/307#issuecomment-1002179897).

The gist is that any arbitrary HTML should be valid when the `slot="start"` or `slot="end"` attribute is added. So in the case of reproducing the search text box from VS Code you could do something along these lines:

```html
<!-- NOTE: DO NOT COPY-PASTE THIS CODE, IT IS INCOMPLETE/INCORRECT -->
<vscode-text-field>
    Label
    <section slot="end" style="display:flex; align-items: center;">
        <vscode-button appearance="icon" aria-label="Toggle case sensitive search">
            <span class="codicon codicon-case-sensitive"></span>
        </vscode-button>
        <vscode-button appearance="icon" aria-label="Toggle whole word search">
            <span class="codicon codicon-whole-word"></span>
        </vscode-button>
        <vscode-button appearance="icon" aria-label="Toggle regex search">
            <span class="codicon codicon-regex"></span>
        </vscode-button>
    </section>
</vscode-text-field>
```

With all that said, this is not a fully complete/working solution because the `vscode-button` with `appearance="icon"` has (ever-so-slightly) incorrect styling for a search text box and also (importantly) does not have toggle functionality built in.

Creating some kind of toggle-able button variant is on our long-term backlog, but we are unfortunately really tightly resourced at this time (myself and one other person split our time between this project and a handful of others) so we probably won't be able to tackle it for a while.

In the meantime, you're always welcome to implement your own version of a toggle-able element since you can put any arbitrary HTML inside the start or end slots of the text field.

**Comment by hawkticehurst** [comment]
Hopefully, that answer helps a bit, let me know if you have any other questions!

**Comment by jedwards1211** [comment]
Ah fantastic, that does help!  I wasn't familiar with slots, it's a different pattern for passing child elements that belong in a certain place from the React way of doing things.

**Comment by hawkticehurst** [comment]
Great happy to hear it! Also haha yeah, I originally started with React and it definitely took a bit of time to get familiar with all the similar-but-slightly-different ways of doing stuff in a web component context
