### ISSUE TITLE
vscode-number component

### ISSUE THREAD

**Issue by scholarsmate** [microsoft/vscode-webview-ui-toolkit#439]
### Feature request

A component that works like standard HTML `input type="number"` to accept numeric inputs.

### Expected behavior

The input component accepts numerics.

### Current behavior

There is currently no work-alike in this library that I'm aware of.

### Use case

Provide an offset to move to, from 0 to the size of the file, for a hex editor.

### Screenshots/references

<img width="352" alt="Screen Shot 2023-01-03 at 5 01 07 PM" src="https://user-images.githubusercontent.com/2205472/210448584-9c343497-76e9-4f43-b95c-f494de414c85.png">

**Comment by lucyydotp** [comment]
`<vscode-text-field type="number" />`seems to do this already, looks like it's just passing the property through to the underlying input
<img width="279" alt="image" src="https://user-images.githubusercontent.com/35287819/213490455-0e8a64cd-3571-4ca2-bb94-a006237471b0.png">

**Comment by triwav** [comment]
It also doesn't support passing in a value of `0` for the value. It just stays blank

**Comment by triwav** [comment]
One work around I found for the `0` issue and might be helpful to you as well @lucyydotp is to make use of the `control` attribute. In my case I'm using Svelte and made a component that uses vscode-text-field internally but deals with the internal input instead which I think should solve your issue as well.

**Comment by hawkticehurst** [comment]
Hey all! I'm doing a pass on old issues and realized I've discussed number fields in another issue but never responded here with the same information (sorry about that 😅).

To explicitly respond to @lucyydotp's suggestion, adding `type="number"` to the `vscode-text-field` will unfortunately _not_ work (or at least it only partially works as you've discovered).

The toolkit is built using a web component framework called [FAST](https://www.fast.design/). In particular, FAST provides a [package of unstyled base components](https://github.com/microsoft/fast/tree/master/packages/web-components/fast-foundation) that we use. In this package, FAST decided to split text fields and number fields into separate components, so the lack of type="number" in the `vscode-text-field` is actually intentional in this case.

The only valid types that can be passed to a FAST text field (and by proxy `vscode-text-field`) are "email", "password", "tel", "text", and "url" ([reference](https://github.com/microsoft/vscode-webview-ui-toolkit/blob/main/src/text-field/README.md#type-attribute)).

On the toolkit side, we haven't added a vscode-number-field component at this point because we've tried to keep the toolkit limited to components that already exist in the VS Code core UI (and a number field isn't one of those components as far as I'm aware). We may change this stance in the future, but like I've said other issues we're very tightly resourced at this time so adding new components to the toolkit isn't something we can really do right now even if we wanted to.

Hope you understand and that this update is helpful! But please do let me know if you have any questions

**Comment by pogi7** [comment]
I decided to make a `vscode-number-field` that accepts numbers for my [open source project](https://github.com/opencaesar/oml-vision/tree/9b93a3c99c4f07172fa1545ad21572d8d03d4616/view/src/components/shared/VSCodeNumberField).  

It probably makes sense if this component is added to the [vscode-webview-ui-toolkit](https://github.com/microsoft/vscode-webview-ui-toolkit)  

Here's an example of what that component looks like in my app
![image](https://github.com/microsoft/vscode-webview-ui-toolkit/assets/108915844/ebff68ab-f594-492c-89f5-3ee375323dc1)

**Comment by hawkticehurst** [comment]
Hi all,

Back with a final update: I'm very sorry to say that the toolkit is being deprecated and all active development will be coming to a close.

There was an [announcement](https://github.com/microsoft/vscode-webview-ui-toolkit/issues/561) last week where you can learn more details and leave any questions or comments you may have.

Beyond that, thank you so much filing this issue and apologies for never getting around to addressing it. It means a lot that you contributed to the improvement of this project. I wish you all the best in your future VS Code extension endeavors!
