### ISSUE TITLE
`vscode-data-grid` with `grid-template-columns` is not respected

### ISSUE THREAD

**Issue by worksofliam** [microsoft/vscode-webview-ui-toolkit#473]
Version defined in package.json:

### Describe the bug

`vscode-data-grid` with `grid-template-columns` is not respected(?)

I am trying to build a data grid where it can fit more than 4 columns in one view.

The data set gets in fine, but there is just so much white space in columns and I assumed `grid-template-columns` might be able to solve this.

<img width="1342" alt="image" src="https://user-images.githubusercontent.com/3708366/233440064-a5f53d0e-5167-4a98-a530-bbc87ffd5d3d.png">

But as you can see, it's generating code with the same attribute, but full of `1fr`.

<img width="1349" alt="image" src="https://user-images.githubusercontent.com/3708366/233440847-4e430248-f636-4ed8-a8d7-874971eb770b.png">

### To reproduce

```html
<vscode-data-grid id="x" grid-template-columns="min-content"></vscode-data-grid>
```

```js
x.columnDefinitions = [...]
x.rowsData = [...];
```

-   OS Version: Mac 12.6
-   Toolkit Version: `^1.0.0`

**Comment by worksofliam** [comment]
Perhaps a different issue, but I will reuse this in case it's related.

I apply `max-content` to the grid like so:

```js
let result = {
    html: `<vscode-data-grid id="${id}" grid-template-columns="${columns.map(c => `max-content`).join(` `)}"></vscode-data-grid>`
};
```

But now when I use this, my column don't align at all D: 

<img width="964" alt="image" src="https://user-images.githubusercontent.com/3708366/233446022-1e1050e2-190c-49cb-9a08-a3543eee2e10.png">

I tested this in CodeSandbox provided in the readme and I change this example to use `max-width` and it turned out ok.

<img width="1090" alt="image" src="https://user-images.githubusercontent.com/3708366/233446199-2b8b6250-499e-477f-9eff-14cc1d5dcbc4.png">

```html
<vscode-data-grid
        id="custom-column-grid"
        grid-template-columns="max-content max-content max-content max-content"
        aria-label="With Custom Column Widths"
></vscode-data-grid>
```

I can't see what I am doing wrong, would love any ideas

**Comment by worksofliam** [comment]
Further digging: I [created my issue in a sandbox](https://codesandbox.io/s/data-grid-sample-forked-xznfrf?file=/index.html) and it's led me to this finding.

* `grid-template-columns` does not work at all with `min-width: max-content;`
* I am using `min-width: max-content;` because I want my users to be able to see many (maybe like 20+) columns. This css prop allows them to do that
* Not using `grid-template-columns` solves the problem of the out of line columns, but it still has all that whitespace in most columns.

**Comment by hawkticehurst** [comment]
Hey @worksofliam! Just chiming in to say I'm a bit swamped for the next 2 weeks so it might take a second for me to circle back this, but I have definitely seen this and will get back to you as soon as I can :)

p.s. thanks for all the thorough notes, super helpful to follow!!

**Comment by hawkticehurst** [comment]
Hey! Finally found a touch of time to do some initial snooping and it looks like this may be an issue we have to bubble up to FAST. Specifically, I can at least speak to your last bullet point:

> Not using grid-template-columns solves the problem of the out of line columns, but it still has all that whitespace in most columns.

It looks like the FAST foundation data grid component will [automatically assign](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-foundation/src/data-grid/data-grid.ts#L991-L1003) grid-template-columns for each row with a value of `1fr` (repeated for each column) if the attribute is not manually defined. 

This should also hopefully give insight into the original issue you were seeing –– when you remove `grid-template-columns` and saw all those `1fr` values you were seeing intentional behavior of the FAST data grid component. If I recall correctly, this behavior might actually be my fault/suggestion (😅) because very very early on during the private preview of the toolkit there were a bunch of issues showing up where people didn't really understand CSS grid and would just see a misshapen grid as the default. Applying `1fr` to each column/row is an easy way to make the data grid "look good/correct".

With that said, I'm still trying to figure out why other valid `grid-template-column` values are not being respected/rendered (i.e. max-content), but thought I'd toss this initial finding here before I inevitably get pulled away to do some other work 😅

**Comment by sklinov** [comment]
@hawkticehurst I think I'm experiencing the same issue
I was trying to build a table with values of different width with column width matching max-content.
But it goes row by row instead of looking like a conventional table.
<img width="686" alt="image" src="https://github.com/microsoft/vscode-webview-ui-toolkit/assets/38185977/ec67bcc5-ca35-4129-950c-ee966126f323">


Here's the sandbox with reproduction
https://codesandbox.io/s/vscode-data-grid-column-width-khn4fj?file=/index.html

**Comment by sklinov** [comment]
BTW, a quick question, @hawkticehurst - is that intentional, that top-level `<VSCodeDataGrid>` has `display: flex; flex-direction: column`? 
I think that may the cause why the grid doesn't want to look like a conventional table

**Comment by sklinov** [comment]
Overall, I ended up with grid `div`s removing `VSCodeDataGridRow` because it ruins the structure of grid.
IMHO, it looks redundant, and the same results could be achieved by setting required `grid-template-columns` to parent element and passing an array of children.
Here's an example https://codesandbox.io/s/zealous-murdock-c8jfm5?file=/src/App.tsx

**Comment by worksofliam** [comment]
@hawkticehurst 

>  If I recall correctly, this behavior might actually be my fault/suggestion (😅) because very very early on during the private preview of the toolkit there were a bunch of issues showing up where people didn't really understand CSS grid

Thanks for looking into this. I let your comment slip! So really what is the suggested fix? Do you think waiting until July for a new FAST version will solve this issue?

**Comment by joacoc** [comment]
Setting the `vscode-data-grid` display to grid solved my issue:
```javascript
const table = document.createElement("vscode-data-grid");
...
table.style.display = "grid";
```

**Comment by hawkticehurst** [comment]
Hello! 

Back again with more updates and I thinkkk I _finally_ understand what's going on here. Sad news, I'm like 98% sure what you're hoping to achieve is impossible given how the FAST data grid has been architected and built 🥲. Less sad news, there seems to be a theoretical workaround but I'm not sure if it will in fact work and what the consequences of that are yet 😅

The gist of the problem is that the `vscode-data-grid-row` really should not exist. In fact, @sklinov is spot on with this comment back in June:

> Overall, I ended up ... removing VSCodeDataGridRow because it ruins the structure of [the] grid.

## The problem

Because the data grid component is split into distinctly separate sub-components (i.e. `vscode-data-grid`, `vscode-data-grid-row`, and `vscode-data-grid-cell`) and those components are web components that use Shadow DOM it means each component can be thought of as having a strong boundary where parent component style changes are not easily passed down to child/grandchildren/etc web components –– aka the normal rules of using web components + shadow dom.

This becomes a problem when using `vscode-data-grid-row` components because they themselves [are styled as CSS grid containers](https://github.com/microsoft/vscode-webview-ui-toolkit/blob/main/src/data-grid/data-grid-row.styles.ts#L21) containing cell components –– the effect is `vscode-data-grid` is just a simple container wrapping a bunch of `vscode-data-grid-rows` that are all distinctly separate grid containers. As a result, there is no way (that I'm aware of) to align columns across multiple CSS grids stacked on top of each other.

This is also why using a simple `display: flex` and `flex-direction: column` inside of `vscode-data-grid` has (for the most part) worked up to this point –– it was just vertically stacking a bunch of CSS grid containers. 

![Image](https://github.com/microsoft/vscode-webview-ui-toolkit/assets/39639992/030ebda6-5a9d-40c5-849b-7c6e6de31926)

Also, @joacoc I'm curious what your specific issue was because changing `vscode-data-grid` to use `display: grid` had no change in trying to resolve @worksofliam's and @sklinov's provided/described issues.

## A solution (?)

With all that said, a casual workaround solution is, in fact, to change `vscode-data-grid` to use `display: grid` and then literally ignore/not use the `vscode-data-grid-row` component at all. Here's some theoretical example code:

```html
<!-- 
  Note: Third and fourth columns are not included for brevity, 
  but they repeat the same pattern as columns one/two 
-->
<vscode-data-grid 
  generate-header="none" 
  style="grid-template-columns: repeat(4, max-content);"
>
  <vscode-data-grid-cell grid-column="1" cell-type="columnheader">
    A Custom Header Title
  </vscode-data-grid-cell>
  <vscode-data-grid-cell grid-column="2" cell-type="columnheader">
    Another Custom Title
  </vscode-data-grid-cell>
  <vscode-data-grid-cell grid-column="1">
    Cell Data Boop
  </vscode-data-grid-cell>
  <vscode-data-grid-cell grid-column="2">
    Cell Data Yummy cool stuff
  </vscode-data-grid-cell>
  <vscode-data-grid-cell grid-column="1">
    Cell Data Wee waa
  </vscode-data-grid-cell>
  <vscode-data-grid-cell grid-column="2">
    Cell Data
  </vscode-data-grid-cell>
  <vscode-data-grid-cell grid-column="1">
    Cell Data Deloop vee
  </vscode-data-grid-cell>
  <vscode-data-grid-cell grid-column="2">
    Cell Data
  </vscode-data-grid-cell>
</vscode-data-grid>
```

In doing this, you will actually be able to achieve a proper table-like data-grid component where columns are aligned, and applying `grid-template-columns: repeat(3, max-content);` will work*. 

*You can try out this code now, but the only remaining problem seems to be the issue where FAST data grids will automatically assign grid-template-columns for each row with a value of `1fr` that I mentioned back in May. This means `style="grid-template-columns: repeat(3, max-content);"` is not being correctly applied when a webview is initially rendered.

The only way I've been able to confirm that it works is by opening the developer tools and toggling the style declaration for  `grid-template-columns` on and off.

Toggle on/off:

![Image](https://github.com/microsoft/vscode-webview-ui-toolkit/assets/39639992/754874de-8a25-487d-b8b0-3be5adcf3201)
![Image](https://github.com/microsoft/vscode-webview-ui-toolkit/assets/39639992/3b0617fa-dd75-446b-8b14-717b66e6768b)

Before:

![Image](https://github.com/microsoft/vscode-webview-ui-toolkit/assets/39639992/5d1e225b-543d-4b84-bc7a-8b54214b2379)

After:

![Image](https://github.com/microsoft/vscode-webview-ui-toolkit/assets/39639992/4f3fb197-d42f-4e1d-af74-4ae1f012be92)

## The real solution

The real/proper solution is to bring this to FAST as an upstream issue or (in all honesty) think about just building a brand new `vscode-data-grid` component from scratch that caters to the specific needs of the community here. But since I know both teams are extremely resource-constrained and likely wouldn't be able to tackle this type of issue for a very long time I'm not actually sure where that leaves us... 

I'm actually keen to have a discussion about this and see if any of you in the community have any thoughts/suggestions/preferences for how to move forward. I'm all ears to any thoughts :)

**Comment by hawkticehurst** [comment]
Hi all,

Back with a final update: I'm very sorry to say that the toolkit is being deprecated and all active development will be coming to a close.

There was an [announcement](https://github.com/microsoft/vscode-webview-ui-toolkit/issues/561) last week where you can learn more details and leave any questions or comments you may have.

Beyond that, thank you so much filing this issue and apologies for never getting around to addressing it. It means a lot that you contributed to the improvement of this project. I wish you all the best in your future VS Code extension endeavors!
