### ISSUE TITLE
React Monaco Editor as a toolkit component

### ISSUE THREAD

**Issue by vardanbansal-harness** [microsoft/vscode-webview-ui-toolkit#477]
Any plans of bringing React Monaco Editor https://microsoft.github.io/monaco-editor/playground.html?source=v0.38.0#example-creating-the-editor-hello-world in the toolkit? 

I tried rendering `MonacoEditor` from `react-monaco-editor` npm package directly. It does render in the view but seeing a very fidgety behaviour during scroll.

**Comment by hawkticehurst** [comment]
Hey @vardanbansal-harness! 

Great question, but unfortunately, no. There are no plans to bring the Monaco Editor into the toolkit, and we probably never will. 

If webviews ever get the ability to use the Monaco Editor I would want this work/API to come from the VS Code core team since they will be able to integrate the editor into webviews far better than I ever could.

**Comment by hawkticehurst** [comment]
Also going to close this issue, but if you have any further questions feel free to comment here and I'll make sure to keep an eye on this thread and respond

**Comment by ArnurKupanov** [comment]
@hawkticehurst Hi!
I'm using monaco editor and the toolkit. Do you happen to know how to change the theme of components when the editor's theme is changed?
