### ISSUE TITLE
Input of type"search" does not fire search event when clicking the clear button

### ISSUE THREAD

**Issue by sketchbuch** [microsoft/vscode-webview-ui-toolkit#503]
### Describe the bug

Search event for input of type search does not fire when clicking the "x" to clear a search button

### Expected behavior

Search event should fire when clicking the "x" to clear a search button

### Current behavior

Event does not fire

### Screenshots

[vscode ui toolkit search input event.webm](https://github.com/microsoft/vscode-webview-ui-toolkit/assets/16445037/06bdf795-dc6a-42d6-a66e-da8f36b9d84a)

### Desktop (please complete the following information):

-   OS Version: Ubuntu 22.04
-   Toolkit Version: v1.2.2

### Additional context

Other events fire fine like keyup, change etc

**Comment by hawkticehurst** [comment]
Hey @sketchbuch! Unfortunately, this is actually expected behavior. We use a library of unstyled-base components from FAST to build the toolkit components and in that library, text fields and search fields are split into two [separate](https://github.com/microsoft/fast/tree/master/packages/web-components/fast-foundation/src/search) [components](https://github.com/microsoft/fast/tree/master/packages/web-components/fast-foundation/src/text-field).

The text field that FAST provides only allows for types: "text", "email", "password", "tel", and "url" ([reference](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-foundation/src/text-field/text-field.options.ts)). While the search component provided by FAST has type "search".

**Comment by hawkticehurst** [comment]
As a result, I'm going to close this issue and ask that you open a new one requesting a search component be added to the toolkit and I'm more than happy to add it to our backlog 😊
