### ISSUE TITLE
Tooltip component

### ISSUE THREAD

**Issue by EcksDy** [microsoft/vscode-webview-ui-toolkit#505]
### Feature request

A tooltip component similar to builtin tooltips in VSCode.

### Screenshots/references
![image](https://github.com/microsoft/vscode-webview-ui-toolkit/assets/994443/3a4fef34-dd17-4c19-b921-0ce0ec25ab8f)

**Comment by hawkticehurst** [comment]
Hey @EcksDy! This behavior/the example you've provided is actually enabled by default HTML behavior! You can add a [`title` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title) to most HTML elements and when hovered the title attribute value will be rendered as a tooltip. 

_This is how the screenshot you provided is implemented in VS Code:_

```html
<!-- Note: I use macOS, thus the difference in keyboard shortcut -->
<h2 title="Explorer (⇧⌘E)">Explorer</h2>
```

Here are a few other examples of how various tooltips are implemented in VS Code as well:

```html
<!-- New file icon button -->
<li role="presentation" title="New File...">
  <a class="codicon codicon-new-file" role="button" aria-label="New File..." aria-checked tabindex="0"></a>
</li>

<!-- Welcome view editor tab -->
<div title="Welcome">
  <div class="monaco-icon-label-container">
    <span class="monaco-icon-name-container">
      <a class="label-name">Welcome</a>
    </span>
  </div>
</div>
```

Since this behavior is enabled by native HTML functionality I'm going to go ahead and close this request. But if you disagree or have any other questions please let me know and I'm happy to discuss 😊.
