### ISSUE TITLE
Impact of FAST Project Re-alignment

### ISSUE THREAD

**Issue by d13** [microsoft/vscode-webview-ui-toolkit#555]
Re: https://github.com/microsoft/fast/issues/6955

Given this news and its dependency on fast-foundation, how do we see this project moving forward?

**Comment by hawkticehurst** [comment]
Hi @d13, sorry it took so long to come back with a response!

We've been working in the background since the announcement trying to figure out how to move forward and unfortunately the conclusion is that we will be sunsetting this project :(

I just opened/pinned [an issue](https://github.com/microsoft/vscode-webview-ui-toolkit/issues/561) with more details. Feel free to leave any questions, comments, etc you may have in that thread

**Comment by hawkticehurst** [comment]
Also going to go ahead and close this issue, but if you have any questions, comments, feedback, etc please feel free to leave a message in the issue thread I just linked to above

**Comment by d13** [comment]
@hawkticehurst thanks for the update
